SELECT
	ROUND(SALARY_BASE / 40) AS DAILY_WAGE,
    COUNT(*) AS USER_COUNT
FROM USERS
WHERE SALARY_BASE BETWEEN 400 AND 900
GROUP BY DAILY_WAGE
ORDER BY USER_COUNT DESC, DAILY_WAGE DESC;

SELECT
	POSITION,
  COUNT(*) AS USER_COUNT
FROM USERS
WHERE SALARY_ADD IS NOT NULL
GROUP BY POSITION
HAVING USER_COUNT > 1;