SELECT LASTNAME,
	USERS.ID_TEAM,
    TEAMS.ID_TEAM, NAME
FROM USERS
INNER JOIN TEAMS
ON USERS.ID_TEAM = TEAMS.ID_TEAM;

SELECT
	LASTNAME,
	SALARY_BASE,
    SALARY_BASE / SALARY_MAX * 100 AS SALARY_MAX_PERCENTAGE
FROM USERS
INNER JOIN POSITIONS
ON USERS.POSITION = POSITIONS.NAME
WHERE POSITION IN ("REGULAR", "SENIOR");

SELECT LASTNAME, NAME, SALARY_BASE, SALARY_MIN, SALARY_MAX
FROM USERS INNER JOIN POSITIONS
ON SALARY_BASE BETWEEN SALARY_MIN AND SALARY_MAX;

SELECT
	E.LASTNAME AS EMPLOYEE,
    B.LASTNAME AS BOSS
FROM USERS E
INNER JOIN USERS B
ON E.ID_BOSS = B.ID_USER;

SELECT
	CONCAT(
		T.NAME,
		" ",
		P.NAME
    ) AS "JOB TITLE"
FROM TEAMS T
CROSS JOIN POSITIONS P
WHERE P.NAME IN ("INTERN", "JUNIOR", "REGULAR", "SENIOR")
	AND T.NAME != "ADMINISTRATION";