INSERT INTO USERS (ID_USER, LASTNAME, ID_TEAM)
VALUES (169, "LEE", 40);

UPDATE
    USERS
SET FIRSTNAME = "AUSTIN"
WHERE FIRSTNAME IS NULL;

UPDATE
    USERS
SET SALARY_BASE = (
    SELECT MIN(SALARY_MIN) FROM POSITIONS
)
WHERE SALARY_BASE IS NULL;

CREATE TABLE ROOMS (
    ID_ROOM INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30),
    AREA DECIMAL(6,2),
    OWNER VARCHAR(30) DEFAULT "NO_OWNER",
    PRIMARY KEY (ID_ROOM)
);

INSERT INTO ROOMS
(NAME, AREA, OWNER)
VALUES("KITCHENETTE", 6, "MEREDITH");

INSERT INTO ROOMS
(NAME, AREA)
VALUES("CONFERENCE", 16.2);