INSERT INTO USERS (ID_USER, LASTNAME, ID_TEAM)
VALUES (169, "LEE", 40);

UPDATE
	USERS
SET FIRSTNAME = "AUSTIN"
WHERE FIRSTNAME IS NULL;

UPDATE
	USERS
SET SALARY_BASE = (
	SELECT MIN(SALARY_MIN) FROM POSITIONS
)
WHERE SALARY_BASE IS NULL;